<a href="https://colab.research.google.com/github/Nadsky096/data-science-bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [3]:
import numpy as np
np.__version__

'1.25.2'

In [ ]:
v1 = np.array([-1,4])
v1

array([0, 4])

In [ ]:
np.linalg.norm(v1)

4.0

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(q-p)


5.0990195135927845

In [ ]:
x = np.array([[5, 3], [3, 9]])
y = np.array([[1], [-1]])
print(x, "\n")
print(y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
Z = np.dot(x, y)

In [ ]:
Z

array([[ 2],
       [-6]])

In [ ]:
Z.shape

(2, 1)

In [ ]:
x = np.array([[2, -1, 3],
              [3, 1, 0]])

y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(x, "\n")
print(y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
np.dot(x, y)

array([[13,  9, -4],
       [ 6,  2, -1]])

In [5]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

In [6]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

In [7]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
A

array([[ 2,  4],
       [-1,  3]])

In [10]:
B = np.linalg.inv(A)

In [11]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [13]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [14]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [15]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [16]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [18]:
A = np.array([[2, 4], [1, -1]])
B = np.array([[10], [-1]])


In [20]:
A_inv = np.linalg.inv(A)

In [21]:
X = np.dot(A_inv, B)

In [22]:
X

array([[1.],
       [2.]])