<a href="https://colab.research.google.com/github/Nadsky096/data-science-bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [2]:
import numpy as np
np.__version__

'1.25.2'

In [ ]:
v1 = np.array([-1,4])
v1

array([0, 4])

In [ ]:
np.linalg.norm(v1)

4.0

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(q-p)


5.0990195135927845

In [ ]:
x = np.array([[5, 3], [3, 9]])
y = np.array([[1], [-1]])
print(x, "\n")
print(y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
Z = np.dot(x, y)

In [ ]:
Z

array([[ 2],
       [-6]])

In [ ]:
Z.shape

(2, 1)

In [ ]:
x = np.array([[2, -1, 3],
              [3, 1, 0]])

y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(x, "\n")
print(y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
np.dot(x, y)

array([[13,  9, -4],
       [ 6,  2, -1]])

In [ ]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

In [ ]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

In [ ]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A

array([[ 2,  4],
       [-1,  3]])

In [ ]:
B = np.linalg.inv(A)

In [ ]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [22]:
np.set_printoptions(precision=4, suppress=True)


In [ ]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [ ]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [ ]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [ ]:
A = np.array([[2, 4], [1, -1]])
B = np.array([[10], [-1]])


In [ ]:
A_inv = np.linalg.inv(A)

In [ ]:
X = np.dot(A_inv, B)

In [ ]:
X

array([[1.],
       [2.]])

In [4]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])

In [5]:
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [6]:
price.sum()

4650.1

In [7]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [8]:
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [9]:
np.sum(price)

4650.1

In [10]:
np.sum(price,axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [11]:
np.min(price,axis=1)

array([11.9, 11.7, 12.2])

In [12]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

In [13]:
mean(price)

NameError: name 'mean' is not defined

In [14]:
np.mean(price)

310.0066666666667

In [15]:
np.mean(price, axis=1)

array([209.94, 409.88, 310.2 ])

In [16]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

In [17]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])

SyntaxError: positional argument follows keyword argument (<ipython-input-20-581ff31aa7dc>, line 1)

In [23]:
np.var(price, axis=0)

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])